pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = "https://maven.quiltmc.org/repository/release" }
    }
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '2.3.21'
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
    versionCatalogs {
        forge {
            from(files("gradle/forge.versions.toml"))
        }
    }
}

rootProject.name = "${mod_id}"
