pluginManagement {
    repositories {
        maven { url = "https://maven.neoforged.net/releases" }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
    versionCatalogs {
        forge {
            from(files("gradle/forge.versions.toml"))
        }
    }
}

rootProject.name = "${mod_id}"

includeBuild('ports/ModularUI') {
    dependencySubstitution {
        substitute module('brachy.modularui:modularui-mc26.2') using project(':')
    }
}
