name: Build Setup
description: Setup for standard Java builds

inputs:
  update-cache:
    description: If cache should be updated
    required: false
    default: 'true'

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up JDK 21
      run: echo "JAVA_HOME=$JAVA_HOME_21_X64" >> "$GITHUB_ENV"

    - name: Validate Gradle wrapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache build directory
      uses: actions/cache@v4
      with:
        path: |
          build/neoForge
          build/neoForm
          build/tmp/.cache/**
        key: "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}"
        restore-keys: "${{ runner.os }}-gradle-"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
        cache-write-only: ${{ inputs.update-cache }}
        generate-job-summary: false
        gradle-home-cache-includes: |
          caches
          notifications
          jdks
          wrapper
