name: build-on-push

on:
  pull_request:
    paths: ['src/**', '**.gradle', 'gradle.properties', 'gradlew**', 'gradle/**']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTION_NUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
      GITHUB_RUN_NUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build
