name: build-on-push

on:
  pull_request:
    paths: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_NUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check Path Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'src/**'
              - '**.gradle'
              - 'gradle.properties'
              - 'gradlew**'
              - 'gradle/**'

      - name: Setup Build
        if: steps.filter.outputs.code == 'true'
        uses: ./.github/actions/build_setup

      - name: Build
        if: steps.filter.outputs.code == 'true'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
          
      - name: Upload Artifact
        if: steps.filter.outputs.code == 'true'
        uses: actions/upload-artifact@v4.0.0
        with:
          name: build output
          path: build/libs/*
          retention-days: 30
