name: Build pull request on push

on:
  pull_request:
    paths: ['**']

# Cancel previous jobs if PR gets another push
concurrency:
  group: PR-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check Path Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'src/**'
              - '*.gradle'
              - 'gradle.properties'
              - 'gradlew*'
              - 'gradle/**'

      - name: Get Build Setup
        if: steps.filter.outputs.code == 'true'
        uses: actions/checkout@v4
        with:
          ref: '1.20.1'
          sparse-checkout: .github/actions
      - name: Setup Build
        if: steps.filter.outputs.code == 'true'
        uses: ./.github/actions/build_setup

      - name: Build
        if: steps.filter.outputs.code == 'true'
        run: ./gradlew assemble --build-cache
          
      - name: Upload Artifact
        if: steps.filter.outputs.code == 'true'
        uses: actions/upload-artifact@v4.0.0
        with:
          name: build output
          path: build/libs/*
          retention-days: 15
