name: Publish 1.20.1 docs via GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: [1.20.1]
    paths: ['docs/**']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    name: build docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './docs'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '1.20.1'
          sparse-checkout: './docs'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r ./requirements.txt
      - uses: actions/cache@v4
        with:
          key: 'mkdocs-cache'
          path: './docs/.cache'
      - name: Deploy 1.20.1 pages to gh-pages branch
        run: mike deploy 1.20.1 --push
      - name: Ensure 1.20.1 is the default version
        run: mike set-default 1.20.1 --push