name: Publish docs via GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: ["1.20.1", "1.21"]
    paths: ['docs/**']

permissions:
  contents: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    name: build docs
    runs-on: ubuntu-latest
    env:
      GIT_COMMITTER_NAME: ci-bot
      GIT_COMMITTER_EMAIL: ci-bot@example.com
      GIT_AUTHOR_NAME: ci-bot
      GIT_AUTHOR_EMAIL: ci-bot@example.com
    defaults:
      run:
        working-directory: './docs'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ github.ref_name }}'
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r ./requirements.txt
      - name: Deploy pages to gh-pages branch
        run: mike deploy "${{ github.ref_name }}" --push
      - name: Ensure 1.20.1 is the default version
        run: mike set-default 1.20.1 --push