name: Publish on Release

on:
  release:
    types: [released]

# TODO: Make it so you can publish releases for each mc-ver individually

jobs:
  meta:
    name: Metadata
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.version }}
      CHANGELOG: ${{ steps.changelog.outputs.changelog }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '1.20.1'
          sparse-checkout: '.github'
      - name: Generate changelog
        id: changelog
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: ./.github/config.json
          toTag: ${{ github.event.release.tag }}
          ignorePreReleases: true
          fetchViaCommits: true
          failOnError: true
      - id: version
        run: echo "version=$(echo ${{ github.event.release.tag_name }} | cut -c2-)" >> $GITHUB_OUTPUT

  publish-20:
    name: 1.20.1
    needs: [ meta ]
    secrets: inherit
    uses: ./.github/workflows/publish.yml
    with:
      simulate: ${{ startsWith(github.event.release.name, 'simulate') || github.repository_owner != 'GregTechCEu' }}
      branch: '1.20.1'
      ver: ${{ needs.meta.outputs.VERSION }}
      tag-name: ${{ github.event.release.tag }}
      release-body: ${{ github.event.release.description }}
      changelog-body: ${{ needs.meta.outputs.CHANGELOG }}

  publish-21:
    name: 1.21.1
    needs: [ meta ]
    secrets: inherit
    uses: ./.github/workflows/publish.yml
    with:
      simulate: ${{ startsWith(github.event.release.name, 'simulate') || github.repository_owner != 'GregTechCEu' }}
      branch: '1.21'
      ver: ${{ needs.meta.outputs.VERSION }}
      tag-name: ${{ github.event.release.tag }}