name: Spotless

on:
  push:
  pull_request:

jobs:
  spotless:
    runs-on: ubuntu-latest

    env:
      MODULE_NAME: CTNH-Core

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Path Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'src/**'
              - 'spotless/**'
              - 'gradle/**'
              - '**/*.gradle'
              - 'settings.gradle'
              - 'gradle.properties'
              - 'dependencies.gradle'
              - 'gradlew'
              - 'gradlew.bat'
              - '.github/**'

      - name: Prepare Workspace
        if: steps.filter.outputs.code == 'true'
        uses: ./.github/actions/ctnh_prepare_workspace
        with:
          token: ${{ github.token }}
          module_name: ${{ env.MODULE_NAME }}

      - name: Spotless Check
        if: steps.filter.outputs.code == 'true'
        working-directory: CTNH-Modules
        run: ./gradlew :modules:${{ env.MODULE_NAME }}:spotlessCheck --warning-mode all
